<?php

include_once('elms_course_versions.features.inc');

/**
 * Implementation of hook_form_alter()
 */
function elms_course_versions_form_alter(&$form, &$form_state, $form_id) {
  //alter the version form
  if ($form_id == 'version_node_form') {
    //always hide purl, they shouldn't need to know anything about it, it just happens
    $form['purl']['value']['#type'] = 'hidden';
    //because purl wants a url, generate a temporary, random one
    //this has to be done because the nid hasn't been set yet and we can't submit the node until we have a PURL identifier yet the NID is supposed to be part of the address, once submitted the node will automatically change thing
    if (arg(1) == 'add') {
      $form['purl']['value']['#default_value'] = '_tmp_'. rand(1,1000);
      $form['themes']['theme']['#default_value'] = 'chamfer';
    }
  }
}