<?php

/**
 * Implements hook_init().
 */
function user_progress_content_init() {
  global $user;
  // have to have access AND be on a node
  if (user_access('set up_content progress record') && $node = menu_get_object()) {
    // calculate what the registry id is, simple as there should be only 1
    $regids = _user_progress_get_registry_ids('up_content');
    // double verify, we should only have 1 otherwise something is wrong
    if (count($regids) > 0) {
      // structure the request
      $upregid = $regids[0]['upregid'];
      $nid = $node->nid;
      $uid = $user->uid;
      $value = 1;
      $data = NULL;
      // this is setting that the user has gone to this page at this time
      _user_progress_set_record($upregid, $uid, $nid, $value, $data);
    }
  }
}
