<?php

include_once('elms_places.features.inc');

/**
 * Implementation of hook_define_highlight_relationship_alter
 */
function elms_places_define_highlight_relationship_alter(&$relationships) {
  if (spaces_access_feature('view', 'elms_places')) {
		$relationships['enhance_content']['highlight_types']['place'] = array(
			'id' => 'places',
			'ref_field' => 'field_location_content_ref',
			'text_field' => 'title',
			'icon' => drupal_get_path('module', 'elms_places') .'/images/place.png',
			'display_text' => t('Reference a Place'),
		);
	}
}