<?php

include_once('elms_icms.features.inc');

/**
 * Implementation of hook_menu_alter().
 */
function elms_icms_menu_alter(&$items) {
  //make the default front-page out of the box course content
  $items['spaces-frontpage']['page callback'] = '_elms_icms_root';
  $items['spaces-frontpage']['access callback'] = 'spaces_access_feature';
  $items['spaces-frontpage']['access arguments'] = array('view', 'elms_content');
  $items['spaces-frontpage']['file'] = 'elms_icms.pages.inc';
  $items['spaces-frontpage']['file path'] = drupal_get_path('module', 'elms_icms');
}