<?php
//Copyright (C) 2011  The Pennsylvania State University
//
//Bryan Ollendyke
//bto108@psu.edu
//
//Keith D. Bailey
//kdb163@psu.edu
//
//12 Borland
//University Park,  PA 16802

/**
 * @file
 * Integrates workflow and purl
 */

/**
 * Implementation of hook_nodeapi().
 */
function workflow_purl_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
  //the group node makes no sense to load to users, redirect to the front-page
  switch ($op) {
  case 'presave':
    //detect a workflow change about to happen
    if ($node->_workflow != $node->workflow) {
      $node->_purl_change = _workflow_purl_get_purl($node);
    }
	dpm($node);
    break;
  case 'update':
    if (isset($node->_purl_change)) {
      $modifier = array(
        'value' => $node->_purl_change,
        'provider' => 'spaces_og',
        'id' => $node->nid,
      );
      purl_save($modifier);
    }
	dpm($node);
    break;
  case 'insert':
  //check for groups created
    if (og_is_group_type($node->type)) {
		dpm($node);
      //need to do extra step with purl rewrite to ensure it has the node and course name in in
      $modifier = array(
        'value' => _workflow_purl_get_purl($node),
        'provider' => 'spaces_og',
        'id' => $node->nid,
      );
      //purl_save($modifier);
    }
  break;
  }
}

//helper function to make modification of purl easier
function _workflow_purl_get_purl($node) {
  $course = node_load($node->field_course_ref[0]['nid']);
  $output = $course->title;
  switch ($node->workflow) {
  case 1:
  case 2:
  case 3: //initial states
    $output .= '_dev_'. $node->nid;
  break;
  case 4: //inactive
    $output .= '_inactive_'. $node->nid;
  break;
  case 5: //offered
    $output .= '_offered_'. $node->nid;
  break;
  case 6: //archive
    $output .= '_archive_'. $node->nid;
  break;
  case 7: //Promo
    $output .= '_promo_'. $node->nid;
  break;
  case 8: //master
    $output .= '_master_'. $node->nid;
  break;
  default:
    $output .= '_dev_'. $node->nid;
  break;
  }
  $output = drupal_strtolower(str_replace(' ', '', $output));
  return $output;
}