<?php
//Copyright (C) 2011  The Pennsylvania State University
//
//Bryan Ollendyke
//bto108@psu.edu
//
//Keith D. Bailey
//kdb163@psu.edu
//
//12 Borland
//University Park,  PA 16802
/**
 * @file
 * Allow for mapping imported RID values directly to user roles in drupal
 */

/**
 * adds user target for role
 */

function feeds_node_helper_feeds_node_processor_targets_alter(&$targets, $content_type) {
  $targets['book_map'] = array(
    'name' => t('Book Parent'),
    'description' => t('Create a book parent relationship'),
    'callback' => 'feeds_node_helper_feeds_set_book_target',
  );
  $targets['type'] = array(
    'name' => t('Node Type'),
    'description' => t('Map value to a node type'),
    'callback' => 'feeds_node_helper_feeds_set_type_target',
  );
  $targets['uuid'] = array(
    'name' => t('UUID'),
    'description' => t('Map value to UUID field'),
    'callback' => 'feeds_node_helper_feeds_set_uuid_target',
  );
}

/**
 * Set the node uuid from an external system.
 */
function feeds_node_helper_feeds_set_uuid_target($node, $target, $value) {
  $node->uuid = $value;
  return $node;
}

/**
 * Set the node type.
 */
function feeds_node_helper_feeds_set_type_target($node, $target, $value) {
  $node->type = $value;
  return $node;
}

/**
 * Set the book parent after import.
 */
function feeds_node_helper_feeds_set_book_target($node, $target, $value) {
  //TODO: This is very specific to the ELMS environment currently
  $group = og_get_group_context();
  $node->book['bid'] = $group->book_nid;
  //load the parent from the UUID, it should have been created prior to creation
  $parentnode = node_get_by_uuid($value);
  if (!$parentnode) {
	return $node;
  }
  //associate the parent correctly now that we've loaded the node
  $node->book['plid'] = $parentnode->book['mlid'];
  return $node;
}

/**
 * Implements hook_ctools_plugin_directory().
 * estabilishes where to look for feeds tamper plugin
 */
function feeds_node_helper_ctools_plugin_directory($module, $plugin) {
  if ($module == 'feeds_tamper') {
    return 'plugins';
  }
}