<?php
//Copyright (C) 2011  The Pennsylvania State University
//
//Bryan Ollendyke
//bto108@psu.edu
//
//Keith D. Bailey
//kdb163@psu.edu
//
//12 Borland
//University Park,  PA 16802
/**
 * @file
 * Allow for mapping imported RID values directly to user roles in drupal
 */

/**
 * adds user target for role
 */

function feeds_node_helper_feeds_node_processor_targets_alter(&$targets, $content_type) {
  $targets['book_map'] = array(
    'name' => t('Book Parent'),
    'description' => t('Create a book parent relationship'),
    'callback' => 'feeds_node_helper_feeds_set_book_target',
  );
}

/**
 * Set the book parent after import.
 */
function feeds_node_helper_feeds_set_book_target($node, $target, $value) {
  //TODO: This is very specific to the ELMS environment currently
  $group = og_get_group_context();
  $node->book['bid'] = $group->book_nid;
  //store this value for the time being, might need to use a temporary value
  $node->book['plid'] = $value;
  return $node;
}
/**
 * Map correctly after import
 */
function feeds_node_helper_feeds_after_import(FeedsImporter $importer, FeedsSource $source) {
  //the import will have a GUI which is a UUID, look up the transformation of UUID to nid in new system
  //$item = db_result(db_query("SELECT * FROM {feeds_node_item} JOIN {book} ON {book}.nid = {feeds_node_item}.nid WHERE guid='%s'", $value));
  dpm($importer);
  dpm($source);
  exit;
}

/**
 * Implements hook_ctools_plugin_directory().
 * estabilishes where to look for feeds tamper plugin
 */
function feeds_node_helper_ctools_plugin_directory($module, $plugin) {
  if ($module == 'feeds_tamper') {
    return 'plugins';
  }
}