<?php

include_once('elms_reaction.features.inc');

/**
 * Implementation of hook_menu().
 */
function elms_reaction_menu() {
  $items = array();
  $items['features/elms_reaction'] = array(
    'title' => 'Settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('elms_reaction_settings'),
    'access callback' => module_exists('spaces') ? 'spaces_access_admin' : 'user_access',
    'access arguments' => module_exists('spaces') ? array() : array('administer site configuration'),
    'type' => MENU_CALLBACK,
    'file' => 'elms_reaction.pages.inc',
  );
  return $items;
}

/**
 * Implementation of hook_link_alter().
 */
function elms_reaction_link_alter(&$links, $node, $comment = NULL) {
  $features = variable_get('spaces_features');
  if (!$features['elms_reaction']) {
    unset($links['reaction_field_related_content']);
  }
}
