<?php
//ELMS: ELMS Helpdesk
//Development Sponsored by The Pennsylvania State University
//ELMS is Copyright (C) 2008-2011  The Pennsylvania State University
//
//Bryan Ollendyke
//bto108@psu.edu
//
//Keith D. Bailey
//kdb163@psu.edu
//
//12 Borland
//University Park,  PA 16802

/**
 * @file
 * Adds functionality that's useful for running a helpdesk
 */

/**
 * Implementation of hook_form_alter().
 */
function elms_helpdesk_form_alter(&$form, &$form_state, $form_id) {
  //trap for the contact page to perform the form alterations
  if ($form_id == 'contact_mail_page') {
    dpm($form);
	global $user;
	dpm($user);
	$form['name']['#default_value'] = 'cool';
	$form['name']['#disabled'] = TRUE;
  }
}