<?php

include_once('elms_course_content.features.inc');

/**
 * Implementation of hook_nodeapi().
 */
function elms_course_content_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
  switch ($op) {
    case 'load':
    //for group nodes, load in the ID of the book outline
    if (og_is_group_type($node->type)) {
    //there's only 1 book per group so load the id and store it in the node object
    //also store the outline mlid to avoid duplicate querying in the future
      $result = db_query("SELECT mlid,{book}.nid FROM {og_ancestry} JOIN {book} ON {book}.nid = {og_ancestry}.nid WHERE {book}.nid = {book}.bid AND group_nid=%d", $node->nid);
      $val = db_fetch_array($result);
      $node->book_outline_mlid = $val['mlid'];
      $node->book_nid = $val['nid'];
    }
  break;
  }
}


/**
 * Implementation of (undocumented) hook_theme_registry_alter().
 */
function elms_course_content_theme_registry_alter(&$vars) {
  //make book navigation function with a jump menu
  $vars['book_navigation']['theme path'] = drupal_get_path('module', 'elms_course_content');
  $vars['book_navigation']['path'] = drupal_get_path('module', 'elms_course_content');
  $vars['book_navigation']['theme paths'] = array(0 => drupal_get_path('module', 'elms_course_content'));
}

/**
 * Implementation of hook_init().
 */
function elms_course_content_init() {
  drupal_add_css(drupal_get_path('module', 'elms_course_content') .'/css/style.css', 'theme');
  //offer to continue where they left off if we can grab it
  if (arg(0) == 'course_content' && module_exists('statistics')) {
    $group = og_get_group_context();
  global $user;
  $result = db_query_range("SELECT {accesslog}.title,{accesslog}.path FROM {accesslog} JOIN {menu_links} ON {menu_links}.link_path = {accesslog}.path JOIN {book} ON {menu_links}.mlid = {book}.mlid JOIN {og_ancestry} ON {book}.nid={og_ancestry}.nid WHERE {accesslog}.uid=%d AND {og_ancestry}.group_nid=%d ORDER BY {accesslog}.timestamp DESC", array($user->uid, $group->nid), 1);
    $val = db_fetch_array($result);
    if ($val['title'] != '') {
      drupal_set_message(t('Continue where you left off? %link', array('%link' => l($val['title'], $val['path']))), 'elms-message');
    }
  }
}

/**
 * Implementation of hook_menu().
 */
function elms_course_content_menu() {
  $items = array();
  $items['course_content'] = array(
    'title' => 'Content',
    'page callback' => '_elms_course_content_root',
    'access callback' => 'spaces_access_feature',
    'access arguments' => array('view', 'elms_course_content'),
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'features',
    'file' => 'elms_course_content.pages.inc',
  );
  $items['features/elms_course_content'] = array(
    'title' => 'Settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('elms_course_content_settings'),
    'access callback' => '_elms_course_content_access_check',
    'access arguments' => module_exists('spaces') ? array() : array('administer site configuration'),
    'type' => MENU_CALLBACK,
    'file' => 'elms_course_content.pages.inc',
  );
  return $items;
}

//helper function for access verification
function _elms_course_content_access_check() {
  if (module_exists('spaces')) {
    return user_access('spaces_access_admin');
  }
  else {
    return user_access('user_access');
  }
}

/**
 * Implementation of hook_block().
 */
function elms_course_content_block($op = 'list', $delta = 0, $edit = array()) {
  if ($op == 'list') {
    $blocks[0] = array(
      'info' => t('ELMS Course Content Nav'),
      'weight' => -10,
      'status' => 0,
    );
    return $blocks;
  }
  elseif ($op == 'view') {
    switch ($delta) {
      case 0:
      //invoke the book module and then alter the title
      $block = module_invoke('book', 'block', 'view', 0);
    $block['subject'] = t('Content');
    $block['title'] = t('Content');
      break;
    }
    return $block;
  }
}

/**
 * Implementation of hook_link().
 */
function elms_course_content_link($type, $object, $teaser = FALSE) {
  $links = array();
  $print_option = variable_get('elms_print_options', 'both');
  if ($type == 'node' && isset($object->book['plid']) && !$teaser && user_access('see printer-friendly version')) {
  $parent = book_link_load($object->book['plid']);
  //verify print setting
  if ($print_option == 'print_lesson' || $print_option == 'print_course' && $object->book['bid'] != $parent['nid']) {
      $links['book_print_lesson'] = array(
      'href' => 'print/book/export/html/'. $parent['nid'],
      'title' => '<img src="/sites/all/modules/print/icons/print_icon.gif" alt="Print Lesson" title="Print Lesson" width="16" height="16" class="print-icon" />',
      'attributes' => array(
        'title' => t('Display a printer-friendly version of this page.'),
        'class' => 'print-page-lesson',
        'onclick' => 'window.open(this.href); return false',
        'rel' => 'nofollow',
      ),
      'html' => 1,
      );
  }
  //verify print setting
  if ($print_option == 'print_course') {
    $links['book_print_course'] = array(
      'href' => 'book/export/html/'. $object->book['bid'],
      'title' => '<img src="/sites/all/modules/print/icons/print_icon.gif" alt="Print Course" title="Print Course" width="16" height="16" class="print-icon" />',
      'attributes' => array(
        'title' => t('Display a printer-friendly version of this page.'),
        'class' => 'print-page-lesson',
        'onclick' => 'window.open(this.href); return false',
        'rel' => 'nofollow',
      ),
      'html' => 1,
      );
  }
  }
  return $links;
}

/**
 * Implementation of hook_link_alter().
 */
function elms_course_content_link_alter(&$links, $node, $comment = NULL) {
  //check print setting
  $print_option = variable_get('elms_print_options', 'both');
  if ($print_option == 'none') {
    unset($links['book_printer']);
  }
}

//helper function for how we render the pager navigation
function _elms_course_content_toc($bid, $exclude = array(), $depth_limit = 10) {
    $tree = menu_tree_all_data(book_menu_name($bid));
    $header = array(t('Table of Contents'));
  $toc = array();
    _elms_course_content_toc_recurse($tree, $toc, $exclude, $depth_limit);
    array_shift($toc);
  return theme('table', $header, $toc, array('id' => 'course-outline'));
}

//helper function for looping through a tree to build out the display
function _elms_course_content_toc_recurse($tree, &$toc, $exclude, $depth_limit) {
  foreach ($tree as $data) {
    if ($data['link']['depth'] > $depth_limit) {
      // Don't iterate through any links on this level.
      break;
    }
    if (!in_array($data['link']['mlid'], $exclude)) {
      $toc[] = array('data' => array(theme('indentation', $data['link']['depth']) . l(t($data['link']['title']), $data['link']['href'])));
      if ($data['below']) {
        _elms_course_content_toc_recurse($data['below'], $toc, $exclude, $depth_limit);
      }
    }
  }
}

/**
 * Implementation of hook_elms_instructional_template().
 */
function elms_course_content_elms_instructional_template() {
  $outline['default'] = array(
    'title' => 'Default Outline',
    0 => array(
      'type' => 'page',
      'title' => 'Lesson @i',
    ),
    1 => array(
      'type' => 'duplicate',
      'parent' => 0,
    ),
  );
  $outline['topical_outline'] = array(
    'title' => 'Topical Lesson Outline',
      0 => array(
        'type' => 'folder',
        'title' => 'Lesson @i',
      ),
      1 => array(
        'type' => 'page',
        'title' => 'Introduction',
        'parent' => 0,
      ),
      2 => array(
        'type' => 'page',
        'title' => 'Content',
        'parent' => 0,
      ),
      3 => array(
        'type' => 'page',
        'title' => 'Wrap up',
        'parent' => 0,
      ),
      4 => array(
       'type' => 'duplicate',
       'parent' => 0,
      ),
      5 => array(
       'type' => 'page',
       'title' => 'Resources',
      ),
  );
  return $outline;
}

/**
 * Implementation of the elms_course_content hook
 */

function _elms_course_content_get_instructional_template($template = 'list') {
  $ary = module_invoke_all('elms_instructional_template');
  if ($template == 'list') {
    $list = array('none' => '');
    foreach ($ary as $key => $params) {
    $list[$key] = $params['title'];
    }
    return $list;
  }
  unset($ary[$template]['title']);
  return $ary[$template];
}

//helper function to create a book for a course version and populate it based on preset chosen
function _elms_course_content_create_root($group, $template = NULL) {
  global $user;
  //creating a blank node
  $node = new stdClass();
  $node->uid = $user->uid;
  $node->type = 'folder';
  $node->status = 1;
  $node->log = 'ELMS outline root created';
  $node->revision = 1;
  $node->book['mlid'] = NULL;
  $node->title = 'Content';
  //settings based on group context in ELMS
  //set group association
  $node->og_groups = array($group->nid => $group->nid);
  $node->og_groups_both = array($group->nid => $group->title);
  //save the book root
  node_save($node);
  //set book outline association automatically
  $node->book['bid'] = $node->nid;
  $node->book['menu_name'] = book_menu_name($node->book['bid']);
  $node->book['module'] = 'book';
  //update outline for new book
  _book_update_outline($node);
  //see if we were passed an instructional template to use, should be
  if ($template != NULL) {
    $id_template = _elms_course_content_get_instructional_template($template);
    $id_template_tmp = $id_template;
    //loop through each item in the defined template and build it as a new book item
    foreach ($id_template_tmp as $key => $book_item) {
    if ($book_item['type'] == 'duplicate') {
    //now replicate
    $backhalf = array_splice($id_template, $key);
    //now grab just the chunk to clone
    $clone_this = array_splice($id_template, $book_item['parent']);
    $clone_this[0]['origin'] = $book_item['parent'];
    foreach ($clone_this as $clone_key => $clone) {
      $clone_this[$clone_key]['clone'] = 1;
    }
    //remove the duplicate request and merge back together
    array_shift($backhalf);
    for ($i=0; $i<$group->field_lesson_count[0]['value']; $i++) {
      $id_template = array_merge($id_template, $clone_this);
    }
    $id_template = array_merge($id_template, $backhalf);
    }
  }
  $count = 1;
  foreach ($id_template as $key => $book_item) {
    if (isset($book_item['origin'])) {
      $current_origin = $key;
      $id_template[$key]['title'] = str_replace('@i', $count, $id_template[$key]['title']);
      $count++;
    }
    if (isset($id_template[$key]['parent']) && isset($id_template[$key]['clone'])) {
      $id_template[$key]['parent'] = $current_origin;
    }
  }
  //now we can run the loop that makes it all
  foreach ($id_template as $key => $book_item) {
    $bookpage = new stdClass();
    $bookpage->uid = $user->uid;
    //if we receive a duplication request, utilize the outline designer duplicate function
    //alter the array to have the correct values
    $bookpage->type = $book_item['type'];
    $bookpage->title = $book_item['title'];
    $bookpage->og_groups = array($group->nid => $group->nid);
    $bookpage->og_groups_both = array($group->nid => $group->title);
    $bookpage->status = 1;
    $bookpage->revision = 1;
    $bookpage->log = 'Template '. $template .' used to create outline page automatically';
    //place it in the book correctly
    $bookpage->book['bid'] = $node->nid;
    $bookpage->book['weight'] = $key-15;
    $bookpage->book['module'] = 'book';
    if ($book_item['type'] == 'link') {
      $bookpage->field_link[0]['value'] = $book_item['link'];
    }
    //we've defined a hierarchy in the template for nested nodes
    if (isset($book_item['parent'])) {
      $bookpage->book['plid'] = $book_map[$book_item['parent']];
    }
    node_save($bookpage);
    $book_map[$key] = $bookpage->book['mlid'];
    $nid_map[$key] = $bookpage->nid;
    }
  }
  watchdog('elms', 'New book outline created for the course version');
}