<?php

include_once('elms_course_content.features.inc');

/**
 * Implementation of hook_menu().
 */
function elms_course_content_menu() {
  $items = array();
  $items['features/elms_course_content'] = array(
    'title' => 'Settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('elms_course_content_settings'),
    'access callback' => module_exists('spaces') ? 'spaces_access_admin' : 'user_access',
    'access arguments' => module_exists('spaces') ? array() : array('administer site configuration'),
    'type' => MENU_CALLBACK,
    'file' => 'elms_course_content.pages.inc',
  );
  return $items;
}
