<?php
// $Id: elms_nav_top.module
//Copyright (C) 2011  The Pennsylvania State University
//
//Bryan Ollendyke
//bto108@psu.edu
//
//Keith D. Bailey
//kdb163@psu.edu
//
//12 Borland
//University Park,  PA 16802
/**
 * @file
 *   Add a right side region for ELMS for containing social elements
 */

/**
 * Implementation of hook_define_region().
 */
function elms_nav_top_define_regions() {
  $region['elms_nav_top'] = array(
    'project' => 'elms_nav_top',
	'js' => 'elms_nav_top.js',
	'css' => 'elms_nav_top.css',
  );
  return $region;
}