<?php
// $Id: elms_nav_left.module
//Copyright (C) 2011  The Pennsylvania State University
//
//Bryan Ollendyke
//bto108@psu.edu
//
//Keith D. Bailey
//kdb163@psu.edu
//
//12 Borland
//University Park,  PA 16802
/**
 * @file
 *   Add a left side region to elms
 */

/**
 * Implementation of hook_define_region().
 */
function elms_nav_left_define_regions() {
  $region['elms_nav_left'] = array(
    'project' => 'elms_nav_left',
	'js' => 'elms_nav_left.js',
	'css' => 'elms_nav_left.css',
  );
  return $region;
}