<?php

include_once('elms_id_best_practices.features.inc');

/**
 * Implementation of hook_menu().
 */
function elms_id_best_practices_menu() {
  $items = array();
  $items['syllabus'] = array(
    'title' => 'Syllabus',
    'page callback' => '_elms_id_best_practices_page_syllabus',
    'access callback' => 'spaces_access_feature',
    'access arguments' => array('view', 'elms_id_best_practices'),
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'features',
    'file' => 'elms_id_best_practices.pages.inc',
    'weight' => -2,
  );
  $items['elms_help'] = array(
    'title' => 'Help',
    'page callback' => '_elms_id_best_practices_page_help',
    'access callback' => 'spaces_access_feature',
    'access arguments' => array('view', 'elms_id_best_practices'),
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'features',
    'file' => 'elms_id_best_practices.pages.inc',
    'weight' => -1,
  );
  $items['features/elms_id_best_practices'] = array(
    'title' => 'Settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('elms_id_best_practices_settings'),
    'access callback' => '_elms_id_best_practices_access_check_admin',
    'access arguments' => module_exists('spaces') ? array() : array('administer site configuration'),
    'type' => MENU_CALLBACK,
    'file' => 'elms_id_best_practices.pages.inc',
  );
	$items['features/id_best_practices'] = array(
    'title' => 'ID Best Practices',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('elms_id_best_practices_settings'),
    'access callback' => '_elms_content_access_check',
		'access arguments' => array(),
    'type' => MENU_LOCAL_TASK,
    'file' => 'elms_id_best_practices.pages.inc',
  );
  $items['admin/elms/id_best_practices'] = array(
    'title' => 'ID Best Practices',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('elms_id_best_practices_settings'),
    'access arguments' => array('administer site configuration'),
    'file' => 'elms_id_best_practices.pages.inc',
  );
  return $items;
}
//helper function for access verification
function _elms_id_best_practices_access_check() {
	//make sure the feature is activated
  if (spaces_access_feature('view', 'elms_id_best_practices')) {
    return user_access('manage features');
  }
	return 0;
}
//helper function for access verification
function _elms_id_best_practices_access_check_admin() {
	//make sure the feature is activated
  if (spaces_access_feature('view', 'elms_id_best_practices')) {
    return user_access('spaces_access_admin');
  }
  return 0;
}

/**
 * Implementation content generation from wysiwyg templates module.
 */
function _elms_id_best_practices_get_template($tid) {
  $body = '';
  //try and match the template to one in the database
  if (module_exists('wysiwyg_template')) {
    $body = db_result(db_query("SELECT body FROM {wysiwyg_templates} WHERE tid=%d", $tid));
  }
  return $body;
}

/**
 * Implementation of hook_book_outline_builder_template().
 */
function elms_id_best_practices_book_outline_builder_template() {
  $outline['unit_outline'] = array(
    'title' => 'Unit / Topical Outline',
      array(
        'type' => 'page',
        'title' => 'Introduction',
        'content' => _elms_id_best_practices_get_template(10),
        'format' => 2,
      ),
      array(
        'type' => 'folder',
        'title' => 'Unit @i',
        'content' => _elms_id_best_practices_get_template(10),
        'format' => 2,
        'duplicate' => TRUE,
        'children' => array(
          array(
            'type' => 'folder',
            'title' => 'Lesson @i',
            'content' => _elms_id_best_practices_get_template(rand(13,15)),
            'format' => 2,
            'duplicate' => 3,
            'children' => array(
              array(
                'type' => 'page',
                'title' => 'Introduction',
                'content' => _elms_id_best_practices_get_template(rand(13,15)),
                'format' => 2,
              ),
              array(
                'type' => 'page',
                'title' => 'Content Page',
                'content' => _elms_id_best_practices_get_template(rand(13,15)),
                'format' => 2,
              ),
              array(
                'type' => 'page',
                'title' => 'Summary',
               'content' => _elms_id_best_practices_get_template(rand(13,15)),
               'format' => 2,
              ),
            ),
          ),
        ),
      ),
  );
  $outline['lesson_outline'] = array(
    'title' => 'Lesson Outline',
      array(
        'type' => 'folder',
        'title' => 'Lesson @i',
        'content' => _elms_id_best_practices_get_template(10),
        'format' => 2,
        'duplicate' => TRUE,
        'children' => array(
            array(
              'type' => 'page',
              'title' => 'Introduction',
              'content' => _elms_id_best_practices_get_template(rand(13,15)),
              'format' => 2,
            ),
            array(
              'type' => 'page',
              'title' => 'Page 1',
              'content' => _elms_id_best_practices_get_template(rand(13,15)),
              'format' => 2,
            ),
						array(
              'type' => 'page',
              'title' => 'Page 2',
              'content' => _elms_id_best_practices_get_template(rand(13,15)),
              'format' => 2,
            ),
						array(
              'type' => 'page',
              'title' => 'Page 3',
              'content' => _elms_id_best_practices_get_template(rand(13,15)),
              'format' => 2,
            ),
            array(
             'type' => 'page',
             'title' => 'Summary',
             'content' => _elms_id_best_practices_get_template(rand(13,15)),
             'format' => 2,
            ),
          ),
      ),
  );
  return $outline;
}