<?php

/**
 * Implements hook_user_progress_init().
 */
function user_progress_jwplayer_init() {
	global $user;
  $group = og_get_group_context();
  //have to be in a group currently AND jwplayer be told to track
  if (isset($group->nid) && user_access('set up_jwplayer progress record') && $node = menu_get_object()) {
    // calculate what the registry id is, simple as there should be only 1
    $regids = _user_progress_get_registry_ids('up_jwplayer', $group->nid);
    // double verify, we should only have 1 otherwise something is wrong
    if (count($regids) == 1) {
			// establish user progress js api with our registry id
			$vars = array(
			  'upregid' => $regids[0]['upregid'],
			  'pressed_play' => false,
			);
      _user_progress_js_setup($vars);
	    // add jwplayer handlers to implement
	    drupal_add_js(drupal_get_path('module', 'user_progress_jwplayer') .'/user_progress_jwplayer.js', 'header');
		}
  }
}
/**
 * Implements hook_user_progress_define_type().
 */
function user_progress_jwplayer_user_progress_define_type() {
  return array(
    'up_jwplayer' => array(
      'name' => t('Media'),
      'value_handler' => 'int',
      'data_handler' => 'int',
    ),
  );
}
