<?php
// $Id: elms_instructional_templates.module

/**
 * @file
 * Instructional Templates hook / API
 */

/**
 * Implementation of hook_elms_instructional_template().
 */
function elms_instructional_templates_elms_instructional_template() {
    $outline['topical_outline'] = array(
	 'title' => 'Topical Lesson Outline',
     0 => array(
       'type' => 'folder',
       'title' => 'Lesson @i',
     ),
	 1 => array(
       'type' => 'page',
       'title' => 'Introduction',
       'parent' => 0,
     ),
	 2 => array(
       'type' => 'page',
       'title' => 'Lesson Content',
       'parent' => 0,
     ),
	 3 => array(
       'type' => 'page',
       'title' => 'Wrap up',
       'parent' => 0,
     ),
	 4 => array(
	   'type' => 'duplicate',
	   'parent' => 0,
	 ),
	 5 => array(
       'type' => 'page',
       'title' => 'Resources',
     ),
    );
  return $outline;
}

/**
 * Implementation of the elms_instructional_template hook
 */
function _elms_instructional_templates_get_instructional_template($template = 'list') {
  $ary = module_invoke_all('elms_instructional_template');
  if ($template == 'list') {
    $list = array('none' => '');
    foreach($ary as $key => $params) {
	  $list[$key] = $params['title'];
    }
    return $list;
  }
  unset($ary[$template]['title']);
  return $ary[$template];
}
