<?php
//ELMS: Contact Helpdesk
//Development Sponsored by The Pennsylvania State University
//ELMS is Copyright (C) 2008-2011  The Pennsylvania State University
//
//Bryan Ollendyke
//bto108@psu.edu
//
//Keith D. Bailey
//kdb163@psu.edu
//
//12 Borland
//University Park,  PA 16802

/**
 * @file
 * Adds functionality that's useful for running a helpdesk
 */

/**
 * Implementation of hook_form_alter().
 */
function contact_helpdesk_form_alter(&$form, &$form_state, $form_id) {
  dpm($form_id);
}